
vich_uploader:
    db_driver: orm       

    twig: true     
    form: true     
    storage: file_system  

    metadata:
        auto_detection: true
        cache: file
        type: attribute

    mappings:
        post_image:
            uri_prefix: /images/posts   
            upload_destination: '%kernel.project_dir%/public/images/posts'   
            namer: Vich\UploaderBundle\Naming\OrignameNamer                
            directory_namer: ~      
            delete_on_remove: true  
            delete_on_update: true  
            inject_on_load: false   
            db_driver: phpcr        